---
title: '2019-06-12'
author: "Pun"
date: "2019年6月12日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load(url("https://www.dropbox.com/s/duh5aaqgl2f5m3z/loopTranscriptData.Rda?raw=1"))
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
studentIds5 <- studentIds[1:5] # 前5筆學號
```

```{r}
studentIds5
seq_along(studentIds5)
```

```{r}
length(studentIds5)
1:length(studentIds5)
```


```{r}
i <- -1
 
print(studentIds5[[i]])
```

```{r}
for (i in seq_along(sequence_source)) {
  print(studentIds5[[i]])
  
}
```

```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
library(stringr)
```

```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
cat("起始狀況\n")
gmailAddress

# for loop
for(i in seq_along(gmailAddress)){
  if(!str_detect(gmailAddress[[i]],"@gmail.com")){
    correctGmailAddress <-
      str_c(gmailAddress[[i]],"@gmail.com")
    gmailAddress[[i]] <- correctGmailAddress
  }
}

cat("修正後狀況\n")
gmailAddress
```

```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
```

```{r}
commitHistory
body
print「第i個」commit的author等於committer的邏輯判斷結果。

i <- 1

(commitHistory[[i]][["commit"]][["author"]][["name"]]==commitHistory[[i]][["commit"]][["committer"]][["name"]]) -> logiResult
print(logiResult)
for loop
for(i in seq_along(commitHistory)){
  (commitHistory[[i]][["commit"]][["author"]][["name"]]==
     commitHistory[[i]][["commit"]][["committer"]][["name"]]) ->
    logiResult
  print(logiResult)  
}
```

```{r}
saveCharacter <- vector("character",5)
saveCharacter

saveNumeric <- vector("numeric",5)
saveNumeric

saveLogical <- vector("logical",5)
saveLogical

saveList <- vector("list",5)
saveList
```

```{r}
# 把"你好"存在saveCharacter第3個位置
saveCharacter # 儲存前
saveCharacter[[3]] <- "你好"
saveCharacter # 儲存後

# 把 72.3 存在saveNumeric第3個位置
saveNumeric # 儲存前
saveNumeric[[3]] <- 72.3
saveNumeric # 儲存後

# 把 TRUE 存在saveLogical第3個位置
saveLogical # 儲存前
saveLogical[[3]] <- TRUE
saveLogical # 儲存後

# 把 list(姓名="小明",電話="02-86741111") 存在saveList第3個位置
saveList # 儲存前
saveList[[3]] <- list(姓名="小明",電話="02-86741111")
saveList # 儲存後
```

```{r}
studentIds5
```

```{r}
i <- -1
 
gpa_fun(studentIds5[[i]]) -> saveGPA5
```

```{r}
saveGPA5
```

```{r}
studentIds <- unique(transcriptDataFinal$學號) # sequence_source
saveGPAs <- vector("numeric",length(studentIds)) # saveContainer
for(i in seq_along(studentIds)){
  saveGPAs[[i]] <- gpa_fun(studentIds[[i]])
}
```

```{r}
saveGPAsWithNames <- saveGPAs
names(saveGPAsWithNames) <- studentIds

saveGPAs[1:5] # 元素沒有名字
saveGPAsWithNames[1:5] # 元素有名字
```

```{r}
load(url("https://www.dropbox.com/s/qnz9paigf61yjus/commitHistory.Rda?raw=1"))
saveCommitAuthor <-
  vector("character",length(commitHistory))

commitHistory



i<- 1

commitHistory[[i]]$commit$author$name -> saveCommitAuthor[[i]]


saveCommitAuthor

saveCommitAuthor <-
  vector("character",length(commitHistory)) # 0.
for(i in seq_along(commitHistory)){
  commitHistory[[i]]$commit$author$name -> saveCommitAuthor[[i]]
}

saveCommitAuthor
```

```{r}
saveEveryThing <- vector("list",length(commitHistory))
```

```{r}
```

```{r}

```