---
title: '2019-04-17'
author: "Pun"
date: "2019年4月17日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(stringr)
library(lubridate)
```




```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```

```{r}
x <- plasticContainer[["greenBox"]] 
x[[1]]
```
```{r}
plasticContainer[["greenBox"]][[1]]
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```

```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```

```{r}
成績單[["個經"]]
成績單[[1]]

```

```{r}
studentRecord[["姓名"]]
studentRecord[["學年平均成績"]][[3]]
```

```{r}
plasticContainer[c("greenBox","redBox")] 
plasticContainer[c(1,2)]
```

```{r}
plasticContainer
extract1 <- plasticContainer[c("greenBox")]
extract2 <- plasticContainer[[c("greenBox")]]
extract1
extract2
```

```{r}
extract1[[1]][1]
extract2[1]
```

```{r}
plasticContainer

length(plasticContainer)
plasticContainer[c(T,F,T)]
```

```{r}
punteuk <- list(pun=214,teuk=701,elf=1106)
```

```{r}
punteuk

length(punteuk)
punteuk[c(T,T,F)]
```

```{r}
plasticContainer$greenBox
plasticContainer[["greenBox"]]

```

```{r}
punteuk$pun
punteuk[["pun"]]
```

```{r}
your_github_username <- "tpemartin"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
```


```{r}
commitCheckStatement
```

```{r}
my_github_username <- "punpun214"
my_practice_reponame <- "107-2-inclass-practice"
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=my_github_username,
    ":repo"=my_practice_reponame
    )
  ) -> commitCheckStatement2
commitCheck2 <- content(GET(commitCheckStatement))
```

```{r}
commitCheckStatement2
```

```{r}
commitCheck[[4]][["commit"]][["author"]][["date"]] -> commitDate
```

```{r}
ymd_hms(commitDate) -> commitDate
with_tz(commitDate,tzone="Asia/Taipei")
```

```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```

```{r}
filmVotingData$Timestamp
filmVotingData[["Timestamp"]]
filmVotingData$`Timestamp`
```
```{r}
library(stringr)
str_split(favoriteTwo,", ") -> favoriteTwoList # 將選擇的兩片split成兩個元素
unlist(favoriteTwoList) -> allVotes # 將list堆疊成atomic vector
table(allVotes) # 計算每個類別的次數
```

```{r}
logiCorrect <- str_length(birthday) == 8
logiCorrect
```

```{r}
favoriteTwo[logiCorrect] -> validFavoriteTwo
validFavoriteTwo
```
