---
title: "2019-03-27-punpun214"
author: "Pun"
date: "2019年3月27日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
```

```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
dtObject
```

```{r}
Sys.timezone()
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```

```{r}
SeoulDateTime <- with_tz(twDateTime,tzone="Asia/Seoul")
```

```{r}
typeof(twDateTime)
```

```{r}
as.double(twDateTime)
```

```{r}
typeof(SeoulDateTime)
```

```{r}
as.double(SeoulDateTime)
```

```{r}
today <- ymd("2019-03-27")
todayE <- mdy("March, 27, 2019")
```

```{r}
as.integer(ymd("1970-01-01"))
as.integer(ymd("1970-01-02"))
as.integer(ymd("2019-03-11"))
```

```{r}
as.integer(mdy("07-01-1983"))
as.integer(mdy("02-14-2000"))
as.integer(mdy("10-29-2011"))
```

```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
```

```{r}
a+bL
class(a+bL)
```

```{r}
aL+bL
class(aL+bL)
```

```{r}
c <- 4

c+a
```

```{r}
a^b
a %% b

```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```
```{r}
twDateTime

twDateTime+1
```

```{r}
twDateTime1 <- ymd_hms("2019-08-11 16:27:27")
twDateTime2 <- ymd_hms("2000-02-01 16:27:27")
```

```{r}
twDateTime1-twDateTime2
```

```{r}
startingDate <- ymd("2000-02-17")
```

```{r}
startingDate + years(1)
```

```{r}
startingDate + dyears(1)
```

```{r}
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```

```{r}
parkDate <- ymd("1983-07-01")
```

```{r}
parkDate + years(17)
```

```{r}
x <- 5
y <- 7

x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```

```{r}
x >= y
x == y
x < y
```

```{r}
x2
y2
x2 < y2
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```

```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4
```

```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```

```{r}
x2
y2
x2 == y2
```

```{r}
x2
is.na(x2)
```

```{r}
x2 == NA
```

```{r}
sum(x2)
sum(x2, na.rm = F)
sum(x2, na.rm = T)
```

