---
title: '2019-04-24'
author: "Pun"
date: "2019年4月24日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Vec1 <- c(1:6) 
Vec1
```

```{r}
Mat1 <- matrix(c(1:6),2,3)
Mat1
```

```{r}
Mat2 <- matrix(c("a","b","c","d"),2,2)
Mat2
```
```{r}
class(Mat2)
typeof(Mat2)
Mat2[[2]]
Mat2[c(T,F,F,T)]
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF
```

```{r}
class(StuDF)
typeof(StuDF)
```

```{r}
StuDF[[2]][[3]]
```

```{r}
class(StuDF$姓名)
```


```{r}
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}

as.data.frame(StuList) -> StuDF3

class(StuDF3)
```


```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
```

```{r}
StuDF3
StuDF4
```

```{r}
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```
```{r}
pickLETTERS <- LETTERS[3:18]
kekeke <- matrix(pickLETTERS,4,4)
kekeke
tolower(kekeke)
toupper(kekeke)
```
```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m) # 轉成小寫
m
toupper(m) # 轉成大寫
m
```

```{r}
kekeke[[5]]
kekeke[c(1,2),c(3,3)]
```


```{r}
matObj1[c(T,F,F,T,F),c(F,T,T)]
```
```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```

```{r}
class(classSurvey)
```
```{r}
classSurvey[c(1:60),c(4:5)]
```

```{r}
classSurvey[,4:5]
```


```{r}
classSurvey[logical_index,]
```

















