---
title: '2019-06-05'
author: "Pun"
date: "2019年6月5日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
utility_cobb_douglass(1,2,0.5,0.8)
```

```{r}
utility_cobb_douglass(1,2,.beta=0.8,.alpha=0.5)
```

```{r}
load(url("https://github.com/tpemartin/github-data/blob/master/loopTranscriptData.Rda?raw=true"))
```

```{r}
gpa_fun(transcriptDataFinal$學號[[1]])
```

```{r}
studentIds <- unique(transcriptDataFinal$學號)
```

```{r}
studentIds5 <- studentIds[1:5]
studentIds5
```

```{r}
for (i in studentIds5) {
  print(i)
}
```

```{r}
for(i in c(1:5)){
  print(i) 
}
```

```{r}
for(i in c(1:5)){
  print(i)
  print(studentIds5[[i]]) # 
}
```

```{r}
seq_along(studentIds5)
for(i in seq_along(studentIds5)){
  print(studentIds5[[i]])
}
```

```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
# 作法一
for(i in gmailAddress){
  print(i)
}
# 作法二
for(i in c(1:4)){
  print(i)
  print(gmailAddress[[i]])
}
# 作法三
for(i in seq_along(gmailAddress)){
  print(i)
  print(gmailAddress[[i]])
}
```

```{r}

```

```{r}

```

```{r}

```












































