---
title: "2019-03-20-punpun214"
author: "Pun"
date: "2019年3月20日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```
```{r}
dialogue <- c("Julia說：'我是豬...豬...豬莉亞。'",
               "Chifu說：'真的喔...我是呆...呆...呆頭鵝'",
              "Julia說：'好呆喔ㄏㄏ'")
cat(dialogue, sep="\n")
```


```{r}
aLogical <- c(T,TRUE,F,FALSE,FALSE)
class(aLogical)
```

```{r}
# 加總向量內的所有元素值。
sum(aLogical)
```

```{r}
typeof(studentMajors)
```
```{r}
levels(studentMajors)
```
```{r}
studentMajors
```
```{r}
as.integer(studentMajors)
```
```{r}
birthplace <- factor(c("台北市", "台北市", "台北市", "台中市", "台中市")
)
as.integer(birthplace)
```
```{r}
typeof(birthplace)
```
```{r}
levels(birthplace)
```
```{r}
as.integer(birthplace)
```

```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算
```
```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算
```
```{r}
stringInteger
trueInteger
```

#Date time

```{r}
library(lubridate)
```
```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```
```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
dtObject
```

```{r}
typeof(dtObject)
```
```{r}
as.double(dtObject)
```
```{r}
Sys.timezone()
```

