---
title: '2019-05-15'
author: "Pun"
date: "2019年5月15日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Vector1 <- letters[1:6]
Vector1

names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}




```


```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
colnames(StuDF2)
names(StuDF2)
```

```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
StuDF2
```
只改col2的名稱

```{r}
colnames(StuDF2)[[2]] <- c("姓名")
colnames(StuDF2)
StuDF2
```

改col2,3的名稱
```{r}
colnames(StuDF2)[c(2,3)] <- c("姓名","成績")
colnames(StuDF2)
StuDF2
```

```{r}
library(stringr)
rownames(StuDF2)
rownames(StuDF2) <- str_c("第",1:5,"筆")
rownames(StuDF2)
StuDF2
```

## 
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" # 元素存在
a[[5]] <- "7" # 元素不存在
a
```


```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
```

```{r}
b[[3]] <- "FALSE"
b[[5]] <- "7"
b
```

```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

```{r}
class(exData3$期間)
```

```{r}
library(lubridate)
exData3$期間 <- ymd(exData3$期間)
class(exData3$期間)
```

```{r}
exData3$isAsiaCrisis <- exData3$期間 <= ymd("1997-06-01") & exData3$期間 >= ymd("1998-12-01")
exData3
```

```{r}
logiAsiaCrisis <- exData3$isAsiaCrisis
exData3[logiAsiaCrisis, ]

```

```{r}
exData3[exData3$isAsiaCrisis == T ,]
exData3[exData3$isAsiaCrisis, ]
```

```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```

```{r}
exampleDF <- data.frame(exchangeRate=c(22,3,3,2,7,12,13),isAsiaCrisis=c(T,T,F,F,F,T,T))
exampleDF
```

```{r}
exampleDF[c(1,2,6,7),]
exampleDF[c(T,T,F,F,F,T,T), ]
```


```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```
```{r}
names(transcriptDataFinal)
```

```{r}
hey <- transcriptDataFinal$學號 == "92aS67fee"
transcriptDataFinal[hey,]
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
class(utility_cobb_douglass)

```

```{r}
park <- function(x,y,.alpha){parkvalue <- x+y^.alpha
return(parkvalue)}
```


```{r}
park(7,1,1983)
```

```{r}
supply_fun <- function(P,a,b){Qs <- a+b*P
return(Qs)}

demand_fun  <- function(c,d,P){Qd <- c-d*P
return(Qd)}

```

```{r}
supply_fun(3,7,2)
demand_fun(6,1,3)
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent
sum(transcriptDataFinal$學期成績[logiChosenStudent]*
  transcriptDataFinal$學分數[logiChosenStudent])/
  sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
```

# 如果常常要算學生的GPA，我們可以定義一個「input學號便可output其GPA」的函數
```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  sum(transcriptDataFinal$學期成績[logiChosenStudent]*
    transcriptDataFinal$學分數[logiChosenStudent])/
    sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
  return(GPA)
}
```
